apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2ftp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-2ftp@sha256:bc621e645f0f29371874e2ea57f98660bee3079c6d38b04d0ab53683613e6bbc
        name: my-nodejs
        resources: {}
status: {}
